### ISSUE TITLE
Other lists that might help

### ISSUE THREAD

**Issue by jkup** [iheanyi/speakers-who-want-a-platform#1]
Hey!

Awesome idea, just wanted to share two lists that I have bookmarked. Not sure if you wanted to add people or maybe even just give a shout out to these lists but figured I'd post them here.

[Tech Women Keynoting at Tech Conferences](https://storify.com/cczona/tech-women-give-keynote-addresses-at-tech-conferen)

[List of women keynote presenters at technical conferences](http://geekfeminism.wikia.com/wiki/List_of_women_keynote_presenters_at_technical_conferences)

**Comment by sotojuan** [comment]
Something I see at conferences is that a lot of the same speakers repeat, many who are "big" in their respective communities. It's kinda discouraging to always compare yourself (because that's who you see speak over and over). I think first time speakers could use some help too, though not sure a GitHub list would be the best.

**Comment by iheanyi** [comment]
@jkup - To be honest, I'll think on this. There could be another repo links to these type of resources, I want to keep the scope of this list as focused as possible. Maybe I'll add in a Further Reading section, not sure yet.
@sotojuan - To be honest, this could be changed into a website as well, but it was the fastest way to get something up and running. Could change things up in the future.

**Comment by sotojuan** [comment]
No problem—most underrepresented people are those who want to speak for the first time anyway, so this repo works as it is.

**Comment by jkup** [comment]
@iheanyi of course! just figured I'd send them your way in case you hadn't seen them before.

**Comment by iheanyi** [comment]
Much appreciated. Gonna close this out and hopefully start a new repo soon with an aggregation of lists and resources for geared towards diversity. 👍
